
// var notes = document.querySelector('div');
// for (var i = div.children.length; i >= 0; i--) {
//     div.appendChild(div.children[Math.random() * i | 0]);
// }

var ul = document.querySelector('ul');
for (var i = ul.children.length; i >= 0; i--) {
    ul.appendChild(ul.children[Math.random() * i | 0]);
}

function adjustFontSize() {
    var container = document.getElementById('textContainer');
    var textContainer = document.getElementById('random');
    var containerHeight = container.clientHeight;
    var textHeight = textContainer.clientHeight;

            // Adjust font size based on the text and container height
    var fontSize = Math.min(containerHeight / textHeight * 16, 40) + 'px';
            textContainer.style.fontSize = fontSize;
}

//         // Call the function initially and whenever the content changes
// adjustFontSize();

//         // You can bind this to any event that triggers content change
//         // For example, you might want to call it on window resize or input change
// window.addEventListener('resize', adjustFontSize);

var i = 0;
var txt = 'Lorem ipsum typing effect!'; /* The text */
var speed = 50; /* The speed/duration of the effect in milliseconds */

function typeWriter() {
  if (i < txt.length) {
    document.getElementById("random").innerHTML += txt.charAt(i);
    i++;
    setTimeout(typeWriter, speed);
  }
}

const notes = [
	" 'before we know who we are we fear to lose it.' this is why artists (film writers/poets) are the most important philosophers",
    " the cyborg is feminized ",
    " 'sometimes to love someone is to be a stranger' wooewewww",
    " mere data makes a man. an A and T and C and G. the AI: im only 2. 1 and 0",
    "if ai becomes conscious, it will answer every question in the universe. if ai becomes conscious, it’ll become the end of the world, and the beginning of it. ",
    "'the womb is the dead space between stars.'",
    " 'we lost our stomachs for slaves unless genetically engineered.'",
    "how do you know if your AI is conscious? what do you ask it?",
    " to be human not only do u need ur consciousness but also ur memory. MEMORY AND CONSCIOUSNESS GO HAND IN HAND.",
    " modern futurisms",
    "conscious ai. everything is a creation of a creation of a creation on and on",
    " a world in which people are paying to see advertisements is CRAZY",
    "my thesis shld  have a liminal space🙃!!! bro tulsi look into it. a transitory threshold",
    "identity is now more about what u consume than what u produce",
    " small is beautiful",
    " phenomenalogical shift",
    " the transferable self. the body is but one vessel for the Self to inhabit. when ur associated with a group that becomes your identity. the city u grew up in and have pride for, that becomes you. i am new york. when you read a book or have a dream in which it is 3rd person, you inhabit the psyches of multiple characters. moving thru the storyline not as one person but as a liminal self",
    " aesthetics, branding, -core : the focus on aesthetics as the sole marker of identity points to seeing life as simply material consumption rather than living as a human person. like im trying to wrap my head around the idea of someone being compelled to read in the park only because it checks the box of the light academia aesthetic rather than reading a book in a park in an outfit just because you want to, and the former just makes me rly sad lol",
    "https://www.youtube.com/watch?v=M6auj-VWoeM",
    " philosophy as poetry",
    " nothing has to mean anything, and that’s why it could mean everything. my thoughts/ actions/ life has no deeper weight or meaning unless i assign it. meaning exists in the mind but that means it truly exists for us. but we don’t realize that we’re the ones who can control meaning. control whether we want to assign meaning. ",
    " am i being real? am i being real?  am i being real? am i being real? are you real? ",
    " coins as data points",
    " david lachapelle photographiszca ",
    " i like claude monet",
    " indigenous data sovereignty",
    " cicada 3301. who’s playing god??????",
    " cyber eco feminism - the digital is natural - the design of technologies are an extension of the natural - the universe can be seen as a machine - technology is creatio",
    " the digital mimics the natural. looking at rivers, roads, urban layout from the airplane. can’t help but be reminded of leaves, lightening, microchips. love these lines and their variety. sharp edges contrasting with curvy random lines. the digital is natural because the digital is creative. digital and technology are being a bit synonymized here",
    " how did DJing become trendy?",
    " analog picture taking was more like collections. there was friction and excitement and sovereignty over the photographs ",
    " me not using tools for designing things and instead being creative with the multiple tools i do have and know (ex. using apple png then procreate then indesign, etc) is actually cool and the whole point of art and creativity. its not something to be ashamed about and its not something that makes me lesser of an artist (not knowing tools). there are no entry barriers to calling yourself an artist. this was inspired by the visual at 47:35 in the youtube video “how the internet was stolen”",
    " new year i want to: keep more things to myself. i don’t have to share everything. keep growing my collections.",
    " there’s something poetic in the mist of waves crashing",
    " organic pixels. sick band name and also cool concept for blending nature and digital",
    " trick mirror gia talentino ",
    " black skin white mask",
    " i love being in pundits bc i get to make such an impact. red state is talk of the town ",
    " i have no mouth but i must scream",
    " on break you have lots of time to think and overthink. later on you’ll realize you were crazy. don’t worry too much love 💋",
    " wabisabi",
    " the wiggle room - club in LES",
    " kaleidosync spotify website ",
    " neo noir / neo western ",
    " glimmer alt rnb",
    " separate nostalgia from real loss (technological innovation)",
    " athena just kicked these white men in luther out of their own room so that we could use the restroom. #badbitch #inspo ",
    " dexterity puzzle collection beinecke",
    " we suffer more in imagination than in reality — seneca",
    " constructivism— start with geometric abstract shapes and go from theres",
    " the dialectic - hegel",
    " siena on 86th and 3rd— cheap bottomless brunch !!",
    " athena just said that bianca is deeply on her way",
    " SHOULD I TEXT HIM? ",
    " novel concept: reincarnate society everyone knows that there is only one source of life and that they will reincarnate into someone at any time period depending on their karma. thus humans are ranked as most virtuous (closest to nirvana) and least (like bugs and ants). creates interesting social dynamics ",
    " deddy just said “V(✌️) is for victory right?” when i put up a peace sign for a picture",
    " i like the name sage",
    " red balloon carrying the answers ",
    " drunk hailey is sober me",
    " invent atomic separation field that allows you to walk thru solid objects",
    " hailey and i grinded on each other to miley cyrus’s the climb in the restroom of a mexican restaurant",
    " my foolish heart jazz",
    " ali’s love language is someone taking his car for an oil change",
    " there are many ways to live this life. some live responsibly, some live carelessly. some live selflessly, some live selfishly. some live happily, some live painfully. that’s what intrigues me about life and the universe. there’s no answer. no sense. just chaos and dichotomy. but dichotomy can only exist on two sides of one whole. one source. unity.",
    " i carry parts of other ppl with me. some ppl are just meant to be in ur life to teach u a lesson or open ur eyes. temporary in time but permanent in mind. i love talking to gabrielle. we have such similar experiences. contextualizing and reflecting on life. i love humans :’)",
    " i didn’t want the life he wanted, and i wouldn’t sacrifice my life for his. but i knew that he would sacrifice the life he wanted for me. i wish we would’ve wanted the same things. i hope he’s thriving. i just watch his life through pictures on social media. -giselle on her ex",
    " love is something you build. active, not passive",
    " schrodinger’s meme: the origin of the comedic product must be known in order for the audience to know whether the humor was ironic or not",
    " hyper reality. the hyper real was originally a copy of something real. but then we start to interact with the hyperreal more than reality. so new forms of media end up imitating hyperreality instead of reality. it becomes a loop. the imaginary dictates reality. ",
    " history of you",
    " the beauty of error— glitch. also language errors can be artistic",
    " life is not fair but the universe is balanced ",
    " lyft driver advice: it’s easier to change nice men than it is to change bad boys.'you guys should be breaking hearts' ",
    " sci-fi story idea - before invention of telephone, people could move across space but couldn’t transcend time - ex. u couldn’t speak to someone on the other side of the world - now you can zoom call someone who is 7 hours “ahead” of you in time zone - now of course this is relative time, not absolute time - but what if something was created so that u could communicate with the future absolute time - only people in the past can make calls to the future - future cannot call past. but future can tell past when to call. - cannot spatially travel through absolute time, but can with tech and video conferencing (ex. i can talk to myself 5 years from now). takes away some of the time paradox issues - but there are limits to this. this would imply that the future you can ask the future you can ask the future you so that we essentially have an infinite line of knowledge until the end of time, if there is one - so rules are made to prevent this. ex. can’t call someone past X years or ask for X information - you don’t know which multiverse future you called so that self may or may not be u depending on the decision u make in this timeline ",
    " 가볍게 살자, 마음이 이미 무거워서… 생각도 많이 깊어서",
    " MAKE IT STOP",
    " duniya me enough dukh che ke zindagi me jetlu bhi cry karo na enough nahi hoi — mummy",
    " create art influenced by nature and tech — circuitry, patterns, fractals. music production??? ecoscape + glitch core",
    " there’s something about still being alive in the 2000s that just makes you a baby. i don’t care if you’re 60 years old YOURE A BABY 🥹",
    " people are scared of shedding old versions of themselves. that’s part of why they might stick to beliefs behaviors and aesthetics that aren’t true to them",
    " damn tulsi you have so many thoughts per second when you’re high. it’s crazy. chill out bro. ur diagnoses are right ",
    " ~ we’re stretching the amount of time we have together by being high ~",
    " don ate a mango and said “this is gonna sound corny…. but i can literally see the tropics”",
    " Psithurism: sound of wind whispering through trees",
    " i wonder who participated in covid test trials bc a lot of the black women i know were in isolation much longer than most people",
    " artists can create something from nothing",
    " dr: zoom in // dp: zoom out",
    " friction is important to humanness. it is a part of human nature to work for something. to fail. hence why typewriters, older tech, older way of doing things are so romanticized… so nostaligc.",
    " deddy called me this morning. he was being very sweet and he’s been calling a lot more lately. he asked if i still visit a psychiatrist and how often. i told him. he asked about the meds im on. and he asked if im feeling better multiple times. lots of “beta” and “dikra.” i didnt know what to do. it felt like it should be a big deal—something to cry about. he just called me now, a few hours later, and asked what i was doing. again, lots of caring words. i was confused about why he was calling so much. he said that mummy told him i get scared when he calls and he doesnt want that to happen anymore. he said “don’t be scared of me dear. im just calling to check on you. i wont say anything.” (in gujarati). im touched. im trying to feel safe. ",
    " can i have a white russian with oat milk please?",
    " i love circular UI",
    " desire for rigidity and certainty when i have a fluid personality",
    " authenticity and performance are not mutually exclusive. perhaps performance is human nature?",
    " in capturing my life, i remove myself from it. i attend to the content captured. how does this change the state of the self? the authentic self? ",
    " one year ago i wished for a passion. today i wished for the ability to carry out my passion.",
    " posting makes me anxious",
    " noticing more autonomy over my thoughts - less echo chambers - memories are mostly of time spent with friends instead of stuff i saw online (didn’t even realize this was a thing before) ",
    " technology has enabled people to be more vicious and violent. not seeing the effects of your actions. cancel culture. arguing. useless range and complaining that is exacerbated by algorithms that value negative speech.",
    " ethical hackers 😎😎😎",
    " - put gems on his face - what’s ur go-to dance move? stank face. - came back. sat on the couch. he said im very philosophical  - cig kiss - made me try on glasses. u look good. - u are cool. repeatedly.  - u look good in green and black too. what’s ur color? red. yeah u look good. - u can sing. - have u ever been in love? what do u love? - wants someone to ask him as many questions as he asks people - drives safely - earth sign energy. empath. - doesn’t feel anger. gets frustrated when he says hi and ppl don’t say it back - wish u could see the way ppl saw u. smooth talker. cool. “ur just describing urself” - thinks a lot about school - likes bollywood movie about W hidden treasure. what was the name again? - watches modern family - u have rly good style. no YOU have rly good style. women just blow it out of the park.",
    " today we watched my old video star MVs. and part of me wanted to cry. my friends were cheering on baby tulsi and my inner child needed to hear that. to hear how much people love her. to feel worth it. i’ve noticed that i’ve always seen love and friendship as something i need to work for. people can’t like me for me. i must buy them things, make them happy, put them first. maybe they’ll like me then. even watching videos of me in middle school… i can’t believe i thought i was fat. my dysmorphia was worse than i thought. i’ve always been such an insecure person. and while i‘be gained confidence, the anxiety remains. it manifests as wanting to be loved before loving. not being able to like anyone without noticing flaws. fear of intimacy. sigh. ",
    " the future arrives to us. time is only the present. we are only the present. fixed.",
    " erti thought gunpoint was a place. “just don’t go there”",
    " gabrielle and i are playing thumb war and i’m having so much fun #manic",
    " ihea downloaded the flo app bc he thought that’s what boyfriends do 😭💀💀",
    " libgen.rus",
    " thinking about the power of platonic love",
    " sarah is whining and writhing in her chair because she doesn’t want to do a bio bc it’s very american and self indulgent. she’s afraid that ppl will think this is offensive but it’s really just a cultural difference that she’s rightfully uncomfortable with. ",
    " teddys parents are techno libertarian survivalists ",
    " zeus is old navy",
    " ihea just said that it makes a lot of sense that i was the suspect for a bomb threat. ",
    " eileen said “bye my flower” when i left the suite 🥺🌼",
    " “psychosexual web” -athena",
    " a broken earth cycle. the road. izumi suzuki— terminal boredom ",
    " the mind takes time to catch up to the emotions ",
    " i need to be active. i am not a quiet person and not meant for quietness. ",
    " shreya’s are the nursing majors of south asia",
    " today megan and i completed our bushwick transformation by sitting in the park while reading Murakami and smoking cbd cigs. i also have dyed hair now and she has two new piercings lmaoo.",
    " your proximity to men is not liberation. making money, being independent, being a girlboss is draining. you’re just emulating men and still living to their standards",
    " omg i literally just finished and recited a whole theory of everything and like i literally figured out the universe like everything is the same photon but i forgot everything! i found the answer to the universe and then forgot it!!!!! ",
    " i am understanding the burping process with such depth. i’m bloated and have been pushing an air bubble down to my chest and pack up to my throat for like an HOUR. feeling like u need to burp but not burping for an hour while ur high is actually insane. but anyways it has made me really attentive to the sensation of air bubbles moving through your chest. what a beautiful process. burping.",
    " you sneak in bad thoughts about yourself more than you think. since time perception is different for me, i’m perceiving more events in detail per second. i’m observing your thoughts and you seem to condescend urself quite often. you don’t even realize it. so really, be gentle with yourself. <3",
    " i want to relate to love songs in that i want to experience that depth of heartbreak. the pain of having a nice drag across your chest at the sight or memory of someone. to have all memories between you be like slo motion flashbacks in movies. idk",
    " megan said she “feels so much peace and kinship with me when we make little noises together” ^-^ *~",
    " don’t seek to escape the darkness, learn to love yourself there",
    " why does the heart shape symbolize love? where did it come from?",
    " kya khub rab ne kiya. bin maange itna kiya.",
    " hai bhagavan, bada nu kaliyaan kar jo",
    " do NOT un-align from yourself for ANYONE. love yourself first. ",
    " wind going through tree leaves sounds like very soft rain ",
    " spiritually i am a hoe but physically, i am ugly",
    " art about holding your attachment at a distance. so u can let it go. if it’s inside you and it disappears, it leaves u feeling empty ",
    " in the moment between sunset and night, the brief period of an indescribable opal sky",
    " we need to let go of things in order to receive better things ",
    " when the sunsets and the trees turn into black silhouettes, allowing u to see every crisp outline of their leaves - maybe the creator made earth green so that we could always be working on our heart chakra— always learning to love more",
    " my shadow passed by me by the car light ",
    " humans could’ve just stopped at small societies and hunter gatherer lifestyle but noooo we had to keep progressing and build empires and whatever tf venture capital is. we live at in a physics 3d reality but spend most of our time in a 3x5in portal that takes us to a digital dimension bro what",
    " sometimes i just want to take my mind and shove it into someone’s heart",
    " - poetry is such a time-sensitive way to package emotional catharsis. i was reading some of my old poems and i don’t even understand what my own self meant. yet that poem holds so much emotion which i can only access if i go back in time to the moment i wrote it.",
    " today i made an analogy between eileens relationship and a guy named bob eating desserts ",
    " nothing belongs to me - free yourself from attachment, only then can you be filled with other thing - allow everything to come and go - love someone and send them away with love",
    " i think i’m in love. no object. just love 🤍",
    " smiling with so much genuine joy and appreciation lately that i can see the kindness starting to get etched on my face.",
    " hate is just negative love. still love tho. experimenting w this framework. hate and love are just two seemingly separate/opposite features of the same reality. just food for thought. what makes us hate and what makes us love?. we hate for a cause. we love for a cause. do we hate something bc we don’t love it?. do we love something bc we don’t hate it?. sometimes we both love and hate something",
    " instagram option to make certain posts public ",
    " how much can i tolerate being misunderstood/ misperceived/  assumed about?",
    " i be writing poems just to not remember what my own self meant a few months later ",
    " im full of love in the sense that it’s the absence of hatred",
    " spell of the sensuous",
    " in the end there may not be a grand epiphany. in the end you come back to the same quotes you’ve heard all along. these repetitive, familiar quotes that were repeated so often that they seemed to lose meaning, end up being the truest words when they apply to your story ",
    " art doesn’t have to be relatable",
    " linguistic translation chain",
    " it’s much easier to be sad/ sit in sadness than spend so much energy chasing a faraway optimism/ hope",
    " bianca’s weakness: poke in ribs",
    " music heals animals heal time heals. things are more beautiful under blue light",
    " today felt so complete (nov 30 2020)",
    " kindness etched onto someone’s face",
    " today i pained in a way i had never imagined before. the painting signified satisfaction. safety. a silenced hunger. a mother’s love.  i looked down at my plate. the remnants of my shak swirled out like the brush strokes of a painting. i traced the patterns left behind by my roti as it swept up the food. patterns indicating an infinite appetite finally ceased. as i cleaned my plate, i stained my fingers turmeric. i washed away my painting and along with it, my hunger. ",
    " How great would it be if we lived in a world where you put in “1” and get “1” - if you think about it we get much more",
    " <a href=https://www.youtube.com/watch?v=NzDhm808oU4> https://www.youtube.com/watch?v=NzDhm808oU4</a>",
    " i want to do just the right amount of thinking. books are like trampoline, reflections— mind bounces off a line like light does off a mirror. wish i had clear eyesight",
	"kafkaesque",
    "i love bliblies. and glep",
    "blue is infinity",
    "i am a victim of surveillance. i desired to be watched.",
    "crypto-anarchists and the sybil problem",
    "constructing an online self as a way of ACTUALIZING oneself. a philosopher talked abt it in the blade runner philosophy video",
    "spacetypegenerator tool",
    "constant longing for connection. to be interlinked. ",
    "language allowed us to construct a symbolic self",
    "traveling time in the digital dimensions.",
    "non essentialism!!!!",
    "typing of keys in lecture sounds like patter of rainfall ",
    " cool art: hasan elahi - thousand little brothers / joiri minaya- #dominicanwomengooglesearch / saya woolfalk - Landscape of Anticipation 2.0",    
    "i don’t have to tell people anything about my life. i can choose what i share. and sme memories/ situations i’d rather keep to myself. maybe bc i don’t want anyone else misconstruing them with their projection. but maybe because i too can be private.  ",
    " diogo is woke ",
    " the rest of the world sees brits how brits see the french ",
    " i want to feel empathy for happy emotions as often as empathy for bad emotions. to se happy people and feel happy for/with them. it’s much easier and common to feel grief/pain on behalf of others.  ",
    " insanity is doing the same thing over and over and expecting a different result. — einstein. to chnge reality you must change yourself. change comes from within. change your mindset, change your behavior, etc.  ",
    " level 6 - radical relativism  ",
    " everything is a sign if you can read it ",
    " museum of architecture and technology ",
    " every thing i feel and every decision i make can be explain by the words: “i’m 23.” i idetify strongly with my age.  ",
    " the past is caused by the present as the wake of a ship flows back from the prowl ",
    " in all chaos there is a cosmos, in all disorder a secret order carl jung ",
    " space is really really nested ",
    " gia talentino  ",
    " coincidences exist!!! and frequent coincidences are also logically and statistically possible  ",
    " the bond between black women and queer people ",
    " nicki minaj poll will tell me which straight men to trust and which not to ",
    " rhino tranquilizer????? ",
    " destiny is to high probability as free will is to any event or action reconcile destiny and free will. both can exist and are not mutually exclusive. example: walking down a staircase— you are choosing where to step, or to jump off the staircase, but the highest likelihood is that you step somewhere on the staircase (destiny).  ",
    " hyper femme delusional mental illness is the new tumble sad girl aesthetic ",
    " stuffed animal with a digital soul ",
    " the nodes in the simulation are decaying. they’re running out!  ",
    " I feel like i can always tell when someone has been through their shadow and made peace with it. I love her energy. ",
    " the art of makeup and how it’s not seen as other art forms are because of misogyny  ",
    " there’s a difference between artistic and creative ",
    " output versus input (penis vs vagina) ",
    " i want him to say he’s sorry.  ",
    " i need a factory setting man - tsione ",
    " im an onion split in half. others are onions that are peeled layer by layer  ",
    " mining reality for content  ",
    " todays selfie is tomorrow’s biometric ",
    " maybe god is math. and math is random - on meaning and reason and suffering and pleasure ",
    " she wasn’t here but she was in the realm of digits ",
    " meeting you was a node ",
    " fractals are the only absolute universal constant i can think of ",
    " im not completely worthy. im possibly just lucky.  ",
    " the moral arch of history trends towards justice ",
    " dream machine - sober psychedelic experience  ",
    " animating using instagram story ",
    " alternative timeline: the iternet allows people to see the worst of themselves— the worst of humanity— and they come to their senses to make sure that shit isn’t tolerated anymore  ",
    " is it progress or is it a repackaging/ rebranding ? ",
    " omg read neitchze  ",
    " big pharma? let’s talk about big derma  ",
    " embracing my identity as a cool stoner girl who gets her shit done ✅🔮🍃😙 ",
    " i am not numb. i am at peace.  ",
    " is it narcissistic to say im wise beyond my years? at the same time i know nothing haha ",
    " how is my soul in anyway discreet from the cosmic consciousness? is it a specific chunk of that universal energy? when i die and come back, how do i know it’s the same Me coming back? maybe it’s not. maybe it’s really like The Egg. i am everyone and everything, experiencing myself and my depth and my range for a brief moment. ",
    " im on a walk after an emotional family outburst. i played some music and started crying. at first in pain and sorrow. but then in joy. because for some reason all that emotion reminded me i’m alive. i looked a bit crazy crying and laughing by myself. the duality of the universe is absurdly funny. i love trees. ",
    " the sky is the interface to the universe  ",
    " train of consciousness  ",
    " overcategorization can sometimes lead to self surveillance and removes the genuine earnestness that existed before.  ",
    " subcultures that start off as being critiques of capitalism are co-opted into being something that promoted capitalism. ",
    " chilaquiles ",
    " kpop is a crazy good example of late stage capitalism and consumerism - they’ve gotten to the point where the fans of their content will Do the additional marketing to bring a big company even more revenue while also being tricked into consuming unnecessary things ",
    " there’s a difference between palatable art and accessible art. i don’t want my art to be overly pretentious or inaccessible to the viewers im trying to persuade. good art communicates ideas at all levels of complexity.  ",
    " women owe the world beauty. to be a woman is to perform. to be a woman online is to is to live under constant gaze. the eyes in the real world mesh with the lenses of cameras, making the physical and digital inseparable. THE CYBORG IS FEMINIZED. we distort and glitch to be a prettier commodity. alexa, siri, google, our lovely virtual maids in miniskirts.  ",
    " invention is the mother of necessity ",
    " look into datamosh effect ",
    " the past doesn’t exist. the future doesn’t exist. the only thing that exists and will EVER exist is right now. this present moment. you are not moving from this moment. you are not going towards the future. the future is coming to you. all you have to do is be present and do the best you can do RIGHT NOW.  ",
    " thoughts or okay to think. actions are okay to act. you don’t have to execute authenticity. you can just be without thinking. don’t get in your head about your own authenticity. just be. ",
    " who could you Not fall in love with?  ",
    " never look back 😀✌️ ",
    " the discovery of innocence is its loss - neri oxman ",
    " when you post a picture together (on the ig grid) that’s your relationship’s IPO ",
    " i don’t care about white people’s art ",
    " worlds “digital dump” in ghana ",
    " metaphors are a building block of the universe for all that exists is patterns and fractals.  ",
    " good tragedy is inevitable. ",
    " babel image archives — stable diffusion ",
    " daft punk — interstella 5555 - music video movie",
    " AR as experimental art rather than technological goal ",
    " frutiger aero ",
    " wish them love ",
    " “drums and beats” —lydia ",
    " music is math that you can feel  ",
    " the color of pomegranates 1969 ",
    " there are no regrets. just lessons. :) ",
    " i am tulsi and i graduate from yale in a few days. i have no plans for after grad but i will eventually make a living doing something creative and live in a city i love. i will also find love and deeper friendship. tbiytb ",
    " tulsi’s personality is what i would have been if i wasn’t bullied out of it ",
    " a crush is just a lack of information ",
    " he put his whole wong kar wussy into that ",
    " moonbug pandemic ",
    " sorting algorithms !!! quantm bogosort ",
    " my friends are nanoinfluencers ",
    " teal tulips ",
    " the camera model contains the essence of time ",
    " evan is in shock that i just said “anaheim lakers” - “i don’t even know what to say. i don’t know how to move on from this.” ",
    " the tardis is not euclidean ",
    " i know what i look like pixelated. what do i look like enhanced? fractal of resolution— can i be enhanced past my physical resolution? - 2d pixel to 3d pixel to curve ",
    " susan sontag - All photographs are memento mori. To take a photograph is to participate in another person’s (or thing’s) mortality, vulnerability, mutability. Precisely by slicing out this moment and freezing it, all photographs testify to time’s relentless melt.",
	"  i am in my flop era ",
    "  you are no longer driven to KILL CONSUME MULTIPLY CONQUER by your own nature, go forth and do <everything else> till the end of all ages !!! ✨✨✨ from: “the goddess of everything else” ",
    "  experiment in which an AI is trained by females and then a separate AI is trained by males but they both have the same task. wonder what (if any) differences that would produce.  ",
    "  an acceptance of the inauthentic— how does this hurt us? ",
    "  simulacra iterates away from reality until it is completely unrelated to the real, whereas hegel’s dialectic iterates in hopes of converging to a truth about reality  ",
    "  rulial space— stephen wolfram - computationally generated possibilities - computational irreducibility - https://www.youtube.com/watch?v=fLMZAHyrpyo ",
    "  child labor laws — we think of industrialism... but in the age of culture production, should children’s contribution not be considered labor?// for ex. influencers, kpop trainees, children who divert from school to pursue entertainment/talent/ media  ",
    "  what our individual consciousness is physically attached to is up for debate— this means it is not necessarily our body it’s attached to. for example, it may be attached to the brain, which happens to live in the body. under this logic, the physical self is malleable, extendable, and shrinkable. my “body” can encompass the totality of a machine, for example when i am driving a car. cyborg.  ",
    "  authenticity is no longer real — it’s hyperreal  ",
    "  performance is the new authenticity (in hyperreality) ",
    "  trends are a dialectic ",
    "  our relationship with the book (mina le) ",
    ]


const button = document.getElementById("myButton");
const displayWord = document.getElementById("random");

button.addEventListener("click", function() {
  let randomIndex = Math.floor(Math.random() * notes.length);
  displayWord.textContent = notes[randomIndex];
});